name: Keep redoc OpenAPI export synchronized
on:
  push:
    paths:
      - "designs/openapi.yaml"
      - .github/workflows/redoc-export.yml
concurrency:
  group: redoc-export-${{ github.ref }}
  cancel-in-progress: true
jobs:
  redoc-export:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build the HTML file
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: "build designs/openapi.yaml -o designs/export/api.html"

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: sync api export html"
          file_pattern: designs/export/api.html
